### PR TITLE
chore: update to v1.6.36, unzip package for Package Control, use XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by mochaaP**

### CODE REVIEW

**Comment by mochaaP** [comment]
Sidenote:
I'm not very sure whether we should add SublimeLSP integration for this, since I don't know what's the role of the `--enable_lsp` option (to index the workspace with LSP?).

To make things worse, SublimeLSP is running on Python 3.3. 🙃 So we either backport this to 3.3, or find some hacks (e.g. unexposed commands as rpc) to bridge the gap.

**Comment by mochaaP** [comment]
cc @fortenforge

**Comment by fortenforge** [comment]
Didn't get a chance to look at this today but I will take a look this week!

**Comment by mochaaP** [comment]
@fortenforge let me know if you have time to look at this. :)

**Review by fortenforge — APPROVED** [review]

**Pull request merged**
